import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( {children}: Readonly<{children: React.ReactNode}> ) {

  const email = "lubiano83@gmail.com";
  const address= "Puente Marchant, Las Trancas, Pinto";
  const year = new Date().getFullYear();
  const derechos = `© ${year} Todos los derechos reservados`;
  const googleMaps = "https://maps.app.goo.gl/Hi7eQXZho17VPcEA6";
  
  return (
    <html lang="es">
      <body className="min-h-screen grid grid-rows-[auto_1fr_auto] font-serif bg-(--anwa-bg) text-(--anwa-text)">
        <Navbar />
        {children}
        <Footer email={email} address={address} derechos={derechos} googleMaps={googleMaps} />
      </body>
    </html>
  );
}
