import type { Metadata } from "next";
import "./globals.css";
import Inicio from "./components/Inicio";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( {children}: Readonly<{children: React.ReactNode}> ) {

  const email = "lubiano83@gmail.com";
  const address= "Puente Marchant, Las Trancas, Pinto";
  const year = new Date().getFullYear();
  const derechos = `© ${year} Todos los derechos reservados`;
  const googleMaps = "https://maps.app.goo.gl/Hi7eQXZho17VPcEA6";
  
  return (
    <html lang="es">
      <body className="min-h-screen grid grid-rows-[auto_1fr_auto] font-serif bg-(--color3) text-(--color4)">
          <Inicio email={email} address={address} derechos={derechos} googleMaps={googleMaps} >
            {children}
          </Inicio>
      </body>
    </html>
  );
}
